#!/bin/bash
node index.js &> debug.log
if [ -s debug.log ] 
then
	sendmail -f From Email -t Target -u Message -m  $(cat debug.log) -s SMTP server:Port -o tls=yes -xu SMTP Username -xp SMTP Password
else
	sendmail -f From Email -t Target -u Message -m  $(cat debug.log) -s SMTP server:Port -o tls=yes -xu SMTP Username -xp SMTP Password
fi
